### ISSUE TITLE
"Certificate strings cannot be blank" issue

### ISSUE THREAD

**Issue by ZetaoYang** [crazy-max/docker-jetbrains-license-server#7]
```

ERROR ResourceDescriptor:124 - Certificate strings cannot be blank


java.lang.IllegalStateException: Certificate strings cannot be blank


	at jetprofile.licenseService.d$a.a(d$a.java:46)


	at jetprofile.licenseService.d$a.a(d$a.java:65)


	at com.jetbrains.ls.floating.rpc.FloatingServerRpcHandler$a$b.a(FloatingServerRpcHandler$a$b.java:50)


	at com.jetbrains.ls.floating.rpc.FloatingServerRpcHandler$a$b.invoke(FloatingServerRpcHandler$a$b.java:20)


	at kara.AsyncActionResultKt$execute$1.invoke(AsyncActionResult.kt:91)


	at kara.AsyncActionResultKt$execute$1.invoke(AsyncActionResult.kt)


	at kara.ActionContextKt.withContext(ActionContext.kt:167)


	at kara.AsyncActionResultKt.execute(AsyncActionResult.kt:90)


	at kara.AsyncActionResultKt.access$execute(AsyncActionResult.kt:1)


	at kara.AsyncActionResultKt$async$1.invoke(AsyncActionResult.kt:122)


	at kara.AsyncActionResultKt$async$1.invoke(AsyncActionResult.kt)


	at kara.AsyncActionResultKt$sam$java_lang_Runnable$0.run(AsyncActionResult.kt)


	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)


	at java.util.concurrent.FutureTask.run(FutureTask.java:266)


	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


	at java.lang.Thread.run(Thread.java:748)
```

**Comment by crazy-max** [comment]
Please provide docker logs and compose file or command

**Comment by ZetaoYang** [comment]
![image](https://user-images.githubusercontent.com/10769951/43987489-1857cdfa-9d54-11e8-9911-11753688eee0.png)

**Comment by ZetaoYang** [comment]
![image](https://user-images.githubusercontent.com/10769951/43987496-2eaf9808-9d54-11e8-9033-bf7a721e573c.png)

**Comment by crazy-max** [comment]
Need server logs not client ones

**Comment by ZetaoYang** [comment]
Sorry, I'm going to try another way to active jetbrains products. And I will close this issue.

**Comment by ZetaoYang** [comment]
![image](https://user-images.githubusercontent.com/10769951/43997425-69a0c572-9e0d-11e8-8964-04d27245e053.png)

**Comment by lazydays79** [comment]
+1, same problem

**Comment by lazydays79** [comment]
[error.txt](https://github.com/crazy-max/docker-jetbrains-license-server/files/2280875/error.txt)

**Comment by crazy-max** [comment]
Ok guys thanks for your input i will take a look on this. Can you try the previous tag `17211` ?

**Comment by ZetaoYang** [comment]
@crazy-max

**Comment by ZetaoYang** [comment]
@crazy-max 
![image](https://user-images.githubusercontent.com/10769951/44007627-acc75730-9ecb-11e8-870f-171c9335d28c.png)

What is admin account of organization?

**Comment by ZetaoYang** [comment]
@crazy-max I have solved this issue. So I will close this issue.
